In [17]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler , OrdinalEncoder
from pandas.api.types import is_numeric_dtype
from sklearn.model_selection import train_test_split

# Dataset Load

In [4]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [10]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

# Data preposeesing

In [8]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
df.duplicated().sum()

0

# Data spliting

In [11]:
x = df.drop(['RowNumber' ,'CustomerId','Surname','Exited'],axis=1)
y = df['Exited']

# Encoding and Scalling apply though for loop

In [14]:
# Creating object for Standerdscaler and ordinalencoder
ord = OrdinalEncoder()
std = StandardScaler()

In [15]:
std = StandardScaler() # creating object for standerdscaler
ord = OrdinalEncoder() # creating object for ordinalencoder

for col in x.columns:
  if not is_numeric_dtype(x[col]):
    x[col]= ord.fit_transform(x[[col]])
  else:
    x[col]= std.fit_transform(x[[col]])

In [16]:
# check x after prepossesing
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,0.0,0.0,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-0.440036,2.0,0.0,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,-1.536794,0.0,0.0,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.501521,0.0,0.0,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,2.063884,2.0,0.0,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276

# Train test split apply

In [18]:
xtrain , xtest , ytrain, ytest = train_test_split(x,y, test_size=.20,random_state=42)

# Applying ANN(Artificial Neural Network)

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense , Dropout , Flatten

ModuleNotFoundError: No module named 'tensorflow'

In [23]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.4.0)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\intel\appdata\roaming\python\python312\site-packages (from tensorflow) (26.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.32.5)
Collecting setuptools (from tensorflow)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\intel\appdata\roaming\python\python312\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.2.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.81.1-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (1.26.4)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\intel\appdata\roaming\python\python312\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\intel\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl (350.9 MB)
   ---------------------------------------- 0.0/350.9 MB ? eta -:--:--
   ---------------------------------------- 2.1/350.9 MB 10.7 MB/s eta 0:00:33
   ---------------------------------------- 4.2/350.9 MB 10.1 MB/s eta 0:00:35
    --------------------------------------- 6.3/350.9 MB 10.2 MB/s eta 0:00:34
    --------------------------------------- 8.1/350.9 MB 9.5 MB/s eta 0:00:37
   - -------------------------------------- 9.7/350.9 MB 9.2 MB/s eta 0:00:38
   - -------------------------------------- 11.3/350.9 MB 8.9 MB/s eta 0:00:39
   - -------------------------------------- 12.8/350.9 MB 8.7 MB/s eta 0:00:40
   - -------------------------------------- 14.4/350.9 MB 8.5 MB/s eta 0:00:40
   - -------------------------------------- 16.0/350.9 MB 8.5 MB/s eta 0:00:40
   -- ------------------------------------- 17.8/350.9 MB 8.3 MB/s eta 0:00:41
   -- ------------------------------------- 19.4/350.9 MB 8.3 MB/s eta 0:00:41
   -- ------------------------------------- 21.0/350.9 MB 8.2 MB/s eta 0:00:41
   -- ------------------------------------- 22.5/350.9 MB 8.2 MB/s eta 0:00:41
   -- ------------------------------------- 24.1/350.9 MB 8.1 MB/s eta 0:00:41
   -- ------------------------------------- 25.7/350.9 MB 8.1 MB/s eta 0:00:41
   --- ------------------------------------ 27.3/350.9 MB 8.0 MB/s eta 0:00:41
   --- ------------------------------------ 28.8/350.9 MB 8.0 MB/s eta 0:00:41
   --- ------------------------------------ 30.4/350.9 MB 8.0 MB/s eta 0:00:41
   --- ------------------------------------ 32.0/350.9 MB 8.0 MB/s eta 0:00:41
   --- ------------------------------------ 33.6/350.9 MB 8.0 MB/s eta 0:00:40
   ---- ----------------------------------- 35.1/350.9 MB 7.9 MB/s eta 0:00:40
   ---- ----------------------------------- 36.7/350.9 MB 7.9 MB/s eta 0:00:40
   ---- ----------------------------------- 38.3/350.9 MB 7.9 MB/s eta 0:00:40
   ---- ----------------------------------- 39.8/350.9 MB 7.9 MB/s eta 0:00:40
   ---- ----------------------------------- 41.4/350.9 MB 7.9 MB/s eta 0:00:40
   ---- ----------------------------------- 43.0/350.9 MB 7.9 MB/s eta 0:00:40
   ----- ---------------------------------- 44.6/350.9 MB 7.8 MB/s eta 0:00:40
   ----- ---------------------------------- 45.1/350.9 MB 7.8 MB/s eta 0:00:40
   ----- ---------------------------------- 46.4/350.9 MB 7.6 MB/s eta 0:00:41
   ----- ---------------------------------- 48.8/350.9 MB 7.7 MB/s eta 0:00:40
   ----- ---------------------------------- 51.1/350.9 MB 7.8 MB/s eta 0:00:39
   ----- ---------------------------------- 52.4/350.9 MB 7.8 MB/s eta 0:00:39
   ------ --------------------------------- 54.3/350.9 MB 7.8 MB/s eta 0:00:39
   ------ --------------------------------- 55.8/350.9 MB 7.8 MB/s eta 0:00:38
   ------ --------------------------------- 57.4/350.9 MB 7.8 MB/s eta 0:00:38
   ------ --------------------------------- 58.7/350.9 MB 7.8 MB/s eta 0:00:38
   ------ --------------------------------- 60.6/350.9 MB 7.8 MB/s eta 0:00:38
   ------- -------------------------------- 62.1/350.9 MB 7.8 MB/s eta 0:00:38
   ------- -------------------------------- 63.7/350.9 MB 7.7 MB/s eta 0:00:38
   ------- -------------------------------- 65.3/350.9 MB 7.7 MB/s eta 0:00:37
   ------- -------------------------------- 66.8/350.9 MB 7.7 MB/s eta 0:00:37
   ------- -------------------------------- 68.4/350.9 MB 7.7 MB/s eta 0:00:37
   ------- -------------------------------- 70.0/350.9 MB 7.7 MB/s eta 0:00:37
   -------- ------------------------------- 71.6/350.9 MB 7.7 MB/s eta 0:00:37
   -------- ------------------------------- 73.1/350.9 MB 7.7 MB/s eta 0:00:36
   -------- ------------------------------- 74.7/350.9 MB 7.7 MB/s eta 0:00:36
   -------- ------------------------------- 76.3/350.9 MB 7.7 MB/s eta 0:00:36
   -------- ------------------------------- 77.6/350.9 MB 7.7 MB/s eta 0:00:36
   -------- ------------------------------- 78.6/350.9 MB 7.6 MB/s eta 0:00:36
   --------- ------------------------------ 80.7/350.9 MB 7.7 MB/s eta 0:00:36
   --------- ------------------------------ 82.6/350.9 MB 7.7 MB/s eta 0:00:35
   --------- ------------------------------ 84.1/350.9 MB 7.7 MB/s eta 0:00:35
   --------- ------------------------------ 85.7/350.9 MB 7.7 MB/s eta 0:00:35
   --------- ------------------------------ 87.3/350.9 MB 7.7 MB/s eta 0:00:35
   ---------- ----------------------------- 88.9/350.9 MB 7.7 MB/s eta 0:00:35
   ---------- ----------------------------- 90.4/350.9 MB 7.7 MB/s eta 0:00:34
   ---------- ----------------------------- 92.0/350.9 MB 7.7 MB/s eta 0:00:34
   ---------- ----------------------------- 93.6/350.9 MB 7.7 MB/s eta 0:00:34
   ---------- ----------------------------- 95.2/350.9 MB 7.7 MB/s eta 0:00:34
   ----------- ---------------------------- 96.7/350.9 MB 7.7 MB/s eta 0:00:34
   ----------- ---------------------------- 98.3/350.9 MB 7.7 MB/s eta 0:00:33
   ----------- ---------------------------- 99.9/350.9 MB 7.7 MB/s eta 0:00:33
   ----------- ---------------------------- 101.4/350.9 MB 7.7 MB/s eta 0:00:33
   ----------- ---------------------------- 103.0/350.9 MB 7.7 MB/s eta 0:00:33
   ----------- ---------------------------- 104.6/350.9 MB 7.7 MB/s eta 0:00:33
   ------------ --------------------------- 106.2/350.9 MB 7.7 MB/s eta 0:00:32
   ------------ --------------------------- 108.0/350.9 MB 7.7 MB/s eta 0:00:32
   ------------ --------------------------- 109.6/350.9 MB 7.7 MB/s eta 0:00:32
   ------------ --------------------------- 110.9/350.9 MB 7.7 MB/s eta 0:00:32
   ------------ --------------------------- 112.5/350.9 MB 7.7 MB/s eta 0:00:32
   ------------ --------------------------- 114.0/350.9 MB 7.7 MB/s eta 0:00:31
   ------------- -------------------------- 115.6/350.9 MB 7.7 MB/s eta 0:00:31
   ------------- -------------------------- 117.4/350.9 MB 7.7 MB/s eta 0:00:31
   ------------- -------------------------- 118.8/350.9 MB 7.7 MB/s eta 0:00:31
   ------------- -------------------------- 120.6/350.9 MB 7.7 MB/s eta 0:00:31
   ------------- -------------------------- 122.2/350.9 MB 7.6 MB/s eta 0:00:30
   -------------- ------------------------- 123.7/350.9 MB 7.6 MB/s eta 0:00:30
   -------------- ------------------------- 125.3/350.9 MB 7.7 MB/s eta 0:00:30
   -------------- ------------------------- 126.9/350.9 MB 7.7 MB/s eta 0:00:30
   -------------- ------------------------- 128.2/350.9 MB 7.6 MB/s eta 0:00:30
   -------------- ------------------------- 130.0/350.9 MB 7.6 MB/s eta 0:00:29
   -------------- ------------------------- 131.6/350.9 MB 7.6 MB/s eta 0:00:29
   --------------- ------------------------ 133.2/350.9 MB 7.6 MB/s eta 0:00:29
   --------------- ------------------------ 134.7/350.9 MB 7.6 MB/s eta 0:00:29
   --------------- ------------------------ 136.3/350.9 MB 7.6 MB/s eta 0:00:29
   --------------- ------------------------ 137.9/350.9 MB 7.6 MB/s eta 0:00:28
   --------------- ------------------------ 139.5/350.9 MB 7.6 MB/s eta 0:00:28
   ---------------- ----------------------- 141.0/350.9 MB 7.6 MB/s eta 0:00:28
   ---------------- ----------------------- 142.6/350.9 MB 7.6 MB/s eta 0:00:28
   ---------------- ----------------------- 144.2/350.9 MB 7.6 MB/s eta 0:00:28
   ---------------- ----------------------- 145.8/350.9 MB 7.6 MB/s eta 0:00:27
   ---------------- ----------------------- 147.3/350.9 MB 7.6 MB/s eta 0:00:27
   ---------------- ----------------------- 148.9/350.9 MB 7.6 MB/s eta 0:00:27
   ----------------- ---------------------- 150.5/350.9 MB 7.6 MB/s eta 0:00:27
   ----------------- ---------------------- 152.3/350.9 MB 7.6 MB/s eta 0:00:27
   ----------------- ---------------------- 153.9/350.9 MB 7.6 MB/s eta 0:00:26
   ----------------- ---------------------- 155.5/350.9 MB 7.6 MB/s eta 0:00:26
   ----------------- ---------------------- 157.0/350.9 MB 7.6 MB/s eta 0:00:26
   ------------------ --------------------- 158.6/350.9 MB 7.6 MB/s eta 0:00:26
   ------------------ --------------------- 160.2/350.9 MB 7.6 MB/s eta 0:00:26
   ------------------ --------------------- 161.7/350.9 MB 7.6 MB/s eta 0:00:25
   ------------------ --------------------- 163.3/350.9 MB 7.6 MB/s eta 0:00:25
   ------------------ --------------------- 164.9/350.9 MB 7.6 MB/s eta 0:00:25
   ------------------ --------------------- 166.5/350.9 MB 7.6 MB/s eta 0:00:25
   ------------------- -------------------- 168.0/350.9 MB 7.6 MB/s eta 0:00:25
   ------------------- -------------------- 169.6/350.9 MB 7.6 MB/s eta 0:00:24
   ------------------- -------------------- 171.2/350.9 MB 7.6 MB/s eta 0:00:24
   ------------------- -------------------- 172.8/350.9 MB 7.6 MB/s eta 0:00:24
   ------------------- -------------------- 174.3/350.9 MB 7.6 MB/s eta 0:00:24
   -------------------- ------------------- 175.9/350.9 MB 7.6 MB/s eta 0:00:23
   -------------------- ------------------- 177.5/350.9 MB 7.6 MB/s eta 0:00:23
   -------------------- ------------------- 179.0/350.9 MB 7.6 MB/s eta 0:00:23
   -------------------- ------------------- 180.6/350.9 MB 7.6 MB/s eta 0:00:23
   -------------------- ------------------- 182.2/350.9 MB 7.6 MB/s eta 0:00:23
   -------------------- ------------------- 183.8/350.9 MB 7.6 MB/s eta 0:00:22
   --------------------- ------------------ 185.3/350.9 MB 7.6 MB/s eta 0:00:22
   --------------------- ------------------ 186.9/350.9 MB 7.6 MB/s eta 0:00:22
   --------------------- ------------------ 188.7/350.9 MB 7.6 MB/s eta 0:00:22
   --------------------- ------------------ 190.1/350.9 MB 7.6 MB/s eta 0:00:22
   --------------------- ------------------ 191.6/350.9 MB 7.6 MB/s eta 0:00:21
   ---------------------- ----------------- 193.2/350.9 MB 7.6 MB/s eta 0:00:21
   ---------------------- ----------------- 194.8/350.9 MB 7.6 MB/s eta 0:00:21
   ---------------------- ----------------- 196.3/350.9 MB 7.6 MB/s eta 0:00:21
   ---------------------- ----------------- 197.9/350.9 MB 7.6 MB/s eta 0:00:21
   ---------------------- ----------------- 199.5/350.9 MB 7.6 MB/s eta 0:00:20
   ---------------------- ----------------- 201.1/350.9 MB 7.6 MB/s eta 0:00:20
   ----------------------- ---------------- 202.6/350.9 MB 7.6 MB/s eta 0:00:20
   ----------------------- ---------------- 204.2/350.9 MB 7.6 MB/s eta 0:00:20
   ----------------------- ---------------- 205.8/350.9 MB 7.6 MB/s eta 0:00:20
   ----------------------- ---------------- 207.4/350.9 MB 7.6 MB/s eta 0:00:19
   ----------------------- ---------------- 208.9/350.9 MB 7.6 MB/s eta 0:00:19
   ----------------------- ---------------- 210.5/350.9 MB 7.6 MB/s eta 0:00:19
   ------------------------ --------------- 212.1/350.9 MB 7.6 MB/s eta 0:00:19
   ------------------------ --------------- 213.6/350.9 MB 7.6 MB/s eta 0:00:19
   ------------------------ --------------- 215.5/350.9 MB 7.6 MB/s eta 0:00:18
   ------------------------ --------------- 217.1/350.9 MB 7.6 MB/s eta 0:00:18
   ------------------------ --------------- 218.6/350.9 MB 7.6 MB/s eta 0:00:18
   ------------------------- -------------- 220.2/350.9 MB 7.6 MB/s eta 0:00:18
   ------------------------- -------------- 221.8/350.9 MB 7.6 MB/s eta 0:00:17
   ------------------------- -------------- 223.6/350.9 MB 7.6 MB/s eta 0:00:17
   ------------------------- -------------- 225.2/350.9 MB 7.6 MB/s eta 0:00:17
   ------------------------- -------------- 226.8/350.9 MB 7.6 MB/s eta 0:00:17
   -------------------------- ------------- 228.3/350.9 MB 7.6 MB/s eta 0:00:17
   -------------------------- ------------- 229.9/350.9 MB 7.6 MB/s eta 0:00:16
   -------------------------- ------------- 231.5/350.9 MB 7.6 MB/s eta 0:00:16
   -------------------------- ------------- 233.0/350.9 MB 7.5 MB/s eta 0:00:16
   -------------------------- ------------- 234.9/350.9 MB 7.5 MB/s eta 0:00:16
   -------------------------- ------------- 236.5/350.9 MB 7.5 MB/s eta 0:00:16
   --------------------------- ------------ 238.0/350.9 MB 7.5 MB/s eta 0:00:15
   --------------------------- ------------ 239.3/350.9 MB 7.5 MB/s eta 0:00:15
   --------------------------- ------------ 241.2/350.9 MB 7.5 MB/s eta 0:00:15
   --------------------------- ------------ 242.7/350.9 MB 7.5 MB/s eta 0:00:15
   --------------------------- ------------ 244.3/350.9 MB 7.5 MB/s eta 0:00:15
   ---------------------------- ----------- 245.9/350.9 MB 7.5 MB/s eta 0:00:14
   ---------------------------- ----------- 247.5/350.9 MB 7.5 MB/s eta 0:00:14
   ---------------------------- ----------- 249.0/350.9 MB 7.5 MB/s eta 0:00:14
   ---------------------------- ----------- 250.6/350.9 MB 7.5 MB/s eta 0:00:14
   ---------------------------- ----------- 252.2/350.9 MB 7.5 MB/s eta 0:00:14
   ---------------------------- ----------- 253.8/350.9 MB 7.5 MB/s eta 0:00:13
   ----------------------------- ---------- 255.3/350.9 MB 7.5 MB/s eta 0:00:13
   ----------------------------- ---------- 256.9/350.9 MB 7.5 MB/s eta 0:00:13
   ----------------------------- ---------- 258.5/350.9 MB 7.5 MB/s eta 0:00:13
   ----------------------------- ---------- 260.3/350.9 MB 7.5 MB/s eta 0:00:13
   ----------------------------- ---------- 261.9/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 263.5/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 265.0/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 266.6/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 268.2/350.9 MB 7.5 MB/s eta 0:00:11
   ------------------------------ --------- 269.7/350.9 MB 7.5 MB/s eta 0:00:11
   ------------------------------ --------- 271.3/350.9 MB 7.5 MB/s eta 0:00:11
   ------------------------------- -------- 272.9/350.9 MB 7.6 MB/s eta 0:00:11
   ------------------------------- -------- 274.5/350.9 MB 7.6 MB/s eta 0:00:11
   ------------------------------- -------- 276.0/350.9 MB 7.6 MB/s eta 0:00:10
   ------------------------------- -------- 277.6/350.9 MB 7.5 MB/s eta 0:00:10
   ------------------------------- -------- 279.2/350.9 MB 7.5 MB/s eta 0:00:10
   ------------------------------- -------- 280.8/350.9 MB 7.5 MB/s eta 0:00:10
   -------------------------------- ------- 282.3/350.9 MB 7.5 MB/s eta 0:00:10
   -------------------------------- ------- 283.1/350.9 MB 7.5 MB/s eta 0:00:09
   -------------------------------- ------- 285.0/350.9 MB 7.5 MB/s eta 0:00:09
   -------------------------------- ------- 287.0/350.9 MB 7.5 MB/s eta 0:00:09
   -------------------------------- ------- 288.6/350.9 MB 7.5 MB/s eta 0:00:09
   --------------------------------- ------ 290.2/350.9 MB 7.5 MB/s eta 0:00:09
   --------------------------------- ------ 291.8/350.9 MB 7.5 MB/s eta 0:00:08
   --------------------------------- ------ 293.3/350.9 MB 7.5 MB/s eta 0:00:08
   --------------------------------- ------ 294.9/350.9 MB 7.5 MB/s eta 0:00:08
   --------------------------------- ------ 296.5/350.9 MB 7.5 MB/s eta 0:00:08
   --------------------------------- ------ 298.1/350.9 MB 7.5 MB/s eta 0:00:08
   ---------------------------------- ----- 299.6/350.9 MB 7.5 MB/s eta 0:00:07
   ---------------------------------- ----- 301.2/350.9 MB 7.5 MB/s eta 0:00:07
   ---------------------------------- ----- 302.8/350.9 MB 7.5 MB/s eta 0:00:07
   ---------------------------------- ----- 304.3/350.9 MB 7.6 MB/s eta 0:00:07
   ---------------------------------- ----- 305.9/350.9 MB 7.6 MB/s eta 0:00:06

  WARNING: The script wheel.exe is installed in 'c:\Users\INTEL\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts saved_model_cli.exe, tf_upgrade_v2.exe, tflite_convert.exe and toco.exe are installed in 'c:\Users\INTEL\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nlkt 4.0.1 requires keras==3.9.0, but you have keras 3.14.1 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip